### ISSUE TITLE
Not all characters are visible in show note

### ISSUE THREAD

**Issue by DanteyPL** [cupcakearmy/cryptgeon#104]
When in note will be used characters `>` and `<`, then everything that will be after character `<` including itself will not be visible in the copy box. Copy button will works correctly and copy proper note.

Steps to reproduce:

1. Create note `>test<test`
1. Show newly created note
1. Visible text will be `>test` and button to copy will copy `>test<test`

Issue not happen if the note will not have `>` before `<`

**Comment by DanteyPL** [comment]
It seems like there is no Input Sanitization and you can use HTML tags in text.

Example:
`<h1>Test Heading 1</h1> <h2>Test Heading 2</h2> <u>Underline</>`
will be formatted and should not

**Comment by cupcakearmy** [comment]
Hey there, there is sanitation :) Basic html elements are allowed.

https://github.com/cupcakearmy/cryptgeon/blob/a2803a13da220729c29a1e76c1e2577eb898ef21/packages/frontend/src/lib/ui/ShowNote.svelte#L42

**Comment by DanteyPL** [comment]
Oh, then working HTML tags are feature. But original problem still persist and can be connected to HTML tags.

**Comment by mengelsen** [comment]
I would also like the ability to include special characters within the secure note: https://github.com/cupcakearmy/cryptgeon/issues/105

The contents of the note should not affect how the page loads.
