### ISSUE TITLE
API

### ISSUE THREAD

**Issue by mkleger** [cupcakearmy/cryptgeon#114]
Cool project!
Is it planned to have an API with which you can create Notes?

**Comment by cupcakearmy** [comment]
The backend, therefore the API, is only a store for encrypted messages. It has no notion of the actual crypto. going on. Basically it's a glorified string storage.
The encryption happens in the client itself, which would make the API kind of useless. There is a CLI client https://github.com/cupcakearmy/cryptgeon?tab=readme-ov-file#cli.
