### ISSUE TITLE
Nginx working example

### ISSUE THREAD

**Issue by delucca** [cupcakearmy/cryptgeon#12]
Hi!

Pretty impressive job :) I've been looking for something like this for a while!

Do you have any working example using Nginx? (:

Thanks!

**Comment by delucca** [comment]
It seems that this conf do the job:
```conf
server {
    listen 80;
    listen [::]:80;
    server_name <server_url>;

    # Enforce HTTPS
    return 301 https://$server_name$request_uri;
}

server {
    listen 443      ssl http2;
    listen [::]:443 ssl http2;
    server_name <server_url>;

    ssl_certificate     /etc/letsencrypt/live/<server_url>/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/<server_url>/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/<server_url>/fullchain.pem;

    location / {
      proxy_pass http://<container_name>:5000/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

But, in any case, I don't know if I forgot something.

**Comment by cupcakearmy** [comment]
Thanks! Been a while since i've written nginx configs. Looks fine, I think in theory there is path missing in the proxy_pass entry. Want to do some testing?

**Comment by delucca** [comment]
> Thanks! Been a while since i've written nginx configs. Looks fine, I think in theory there is path missing in the proxy_pass entry. Want to do some testing?

Thanks for your reply :)

I've hosted it in this URL: https://cryptgeon.fonsecafloriano.com/

It seems to be working as expected. Don't know if I've missed something.

**Comment by cupcakearmy** [comment]
Ok if it works I'll believe you :)
I'll add it in a example folder 🥳

**Comment by cupcakearmy** [comment]
https://github.com/cupcakearmy/cryptgeon#nginx-proxy added :)
