### ISSUE TITLE
'rediss//' does not work (double 'ss' for TLS)

### ISSUE THREAD

**Issue by karlismea** [cupcakearmy/cryptgeon#121]
TLS support missing. Can't deploy it in AWS where TLS is enforced for ElasticCache Redis. 

https://github.com/cupcakearmy/cryptgeon/blob/19bf1556531c5e6752ad670978909923e73c6753/packages/backend/Cargo.toml#L25C1-L25C14

Should be 
```
redis = { version = "0.23.0", features = ["tls"] }
```
Today
```
redis = 0.23
```

**Comment by cupcakearmy** [comment]
Thanks for opening the issue, makes total sense.

According to the package:
> Deprecation Notice: If you were using the tls or async-std-tls-comp features, please use the tls-native-tls or async-std-native-tls-comp features respectively.

```
redis = { version = "0.25.2", features = ["tls-native-tls"] }
```
