### ISSUE TITLE
Size limit set to 512 MiB getting Max 379 MiB

### ISSUE THREAD

**Issue by mariushosting** [cupcakearmy/cryptgeon#129]
I have SIZE_LIMIT: 512 MiB
in my environment variable.

Cryptgeon frontend says it's only 379 MiB

![379 mib](https://github.com/cupcakearmy/cryptgeon/assets/37554361/70625aa3-ee3c-42bf-b3e1-dff5c6d822e6)

@cupcakearmy

**Comment by cupcakearmy** [comment]
Hi there!
This is expected behaviour. If you read the table about the enc variables in the readme, it says that the dringend will show approx. 35% less, due to encoding overhead.
