### ISSUE TITLE
Custom Password Toggle Ignores Status

### ISSUE THREAD

**Issue by hxs-sma** [cupcakearmy/cryptgeon#137]
**Description**
In the advanced options, there is a toggle for "custom password." Even when this toggle is disabled, clicking on the dice icon can generate a random password, which is then used to encrypt the note.

**Expected Behavior**
A custom password should only be used if the toggle is switched to enabled. If the toggle is disabled, the text field should be ignored, even if it contains a password.

**Suggested Solution**
Modify the behavior to check the status of the "custom password" toggle before using any password from the text field. If the toggle is disabled, the password in the text field should be ignored.

**Environment**
Browser: Microsoft Edge Version 126.0.2592.68 (64-bit)
Cryptgeon Version: v2.6.1

**Comment by cupcakearmy** [comment]
We don't have custom passwords anymore, will close for now

**Comment by cupcakearmy** [comment]
Thanks for reporting, i misread and you are absolutely right.
