### ISSUE TITLE
File Upload Size Limit Not Enforced, Leading to Decryption Errors

### ISSUE THREAD

**Issue by hxs-sma** [cupcakearmy/cryptgeon#138]
**Description**
When uploading a file, a maximum file size is displayed in the web frontend. However, it is possible to upload files larger than this limit. The uploader does not encounter any errors during the process - encrypting, uploading, and generating the download link all proceed as expected. However, when the link is opened and "show note" is clicked, the initial "downloading..." message appears, but once completed, the following error occurs: "wrong password. could not decipher. probably a broken link. note was destroyed."

**Expected Behavior**
The system should enforce the configured file size limit and prevent files larger than the specified limit from being uploaded. If a file exceeds the limit, the uploader should receive an immediate error message, and the upload process should be aborted.

**Suggested Solution**
Enforce the configured file size limit strictly during the upload process.
Display an immediate error message to the user if the uploaded file exceeds the configured limit.

**Environment**
Browser: Microsoft Edge Version 126.0.2592.68 (64-bit)
Cryptgeon Version: v2.6.1
Configured size limit: 512 MiB
Size limit displayed in web frontend: 379 MiB
Uploaded file size: 522 MiB

**Comment by cupcakearmy** [comment]
yes, this is being a bit flacky with actix for some reason. [I'm rewriting in axum](https://github.com/cupcakearmy/cryptgeon/pull/147), which I'm confident will fix the issue finally
