### ISSUE TITLE
Upgrade to version 2.7.0 issue

### ISSUE THREAD

**Issue by nicfab** [cupcakearmy/cryptgeon#146]
I upgraded `cryptgeon` by the following commands:
- `docker compose down`
- `docker compose pull`
- `docker compose up -d`

However, going to the instance and selecting `about` at the bottom, I see 2.6.1.

What am I wrong?

**Comment by nicfab** [comment]
I was too fast in upgrading.
Now I see the latest version.

**Comment by cupcakearmy** [comment]
Happened to me too xD
it takes ~1h to build and push the images, because also arm images are built on qemu :)
