### ISSUE TITLE
Form submitted when creating a password

### ISSUE THREAD

**Issue by japapu1** [cupcakearmy/cryptgeon#150]
Heyho ...

I have a little problem with the tool.

When I am creating a new secret and then creating a new custom password (via the dice button) the form will be submitted and I have no option to view/copy the password. Also the form will be submitted when clicking the view button in the custom password field.

Is this the correct behavior?

I tested it with chrome and also firefox.
I am running version 2.8.1 in docker.

**Comment by cupcakearmy** [comment]
Thanks for reporting, should be fixed
