### ISSUE TITLE
Feature Request: Multilanguage capable

### ISSUE THREAD

**Issue by MalteKiefer** [cupcakearmy/cryptgeon#17]
Hello,

it would be great if you could maybe offer this application in multiple languages.
For example a 

```
ENV LANGUAGE=EN
```

Would add the German translation.

**Comment by cupcakearmy** [comment]
I was thinking about that. If you are willing to create the german variant sure!
However I would not make in an ENV variable, but rather load the locales for the user browser, so everyone gets their locale in the browser. I'll make an update today/tomorrow to include the logic for that, then you can add the german variant. Is that fine?

**Comment by MalteKiefer** [comment]
That would be nice

**Comment by cupcakearmy** [comment]
Have a look here https://github.com/cupcakearmy/cryptgeon/blob/main/frontend/locales/de.json
