### ISSUE TITLE
Feature Request: Disable fiel upload and advanced settings

### ISSUE THREAD

**Issue by MalteKiefer** [cupcakearmy/cryptgeon#18]
It would be good if per enviroment variable certain functions could be deactivated.

For example, if you do not want to allow files, or users should not be able to see the additional settings.

**Comment by johnnyq** [comment]
Some possible modifications could also be

the ability to change the message on the front page.
`
Easily send fully encrypted, secure notes or files with one click. Just create a note and share the link.`

The removal and or customization of the bottom links /home /about /code

After Create 

The ability add or modify message 

```
availability:
the note is not guaranteed to be stored as everything is kept in ram, if it fills up the oldest notes will be removed.
(you probably will be fine, just be warned.)
```

Also the option to enforce Number of View and or Expiration Date

**Comment by cupcakearmy** [comment]
I don't see why removing links should be encouraged tbh, same goes for the text.

I will add customization for:
- Max views
- Max expiration (minutes)
- advanced options enabled

The toggle for file does not make much sense imo as the size limits are the same for text and file and would restrict users unecesarily.
