### ISSUE TITLE
Could not create note.

### ISSUE THREAD

**Issue by AgentSphynx** [cupcakearmy/cryptgeon#20]
![Screenshot_20220209-215305](https://user-images.githubusercontent.com/89485627/153288786-489f99b0-76e6-4474-9c29-d5d6e9fb84b6.png)
![IMG_20220209_215600](https://user-images.githubusercontent.com/89485627/153288787-0db9fe26-4609-44cb-82de-85d5f5a25e48.jpg)

Hi,
I have this issue. I pulled it with the Standard docker yml config and i only have changed from 4mb to 100mb. What is wrong? Kind regards

**Comment by cupcakearmy** [comment]
Are you creating a text note?

**Comment by cupcakearmy** [comment]
Do you have any error logs from the server? it's kind of hard to tell exactly without an error code

**Comment by IsusVonBier** [comment]
Are you using reverse proxy?

**Comment by cahspar** [comment]
Yepp

**Comment by AgentSphynx** [comment]
> 

Me too

**Comment by cupcakearmy** [comment]
The error indicated that the backend cannot connect/find the memcached server. I'm quite positive thats the issue here

**Comment by cupcakearmy** [comment]
Feel free to reopen if needed.

**Comment by marvinjuette** [comment]
I use docker to deploy crpytgeon. I ran into a similar problem. But I don't seem to get any logs inside of the containers :/
