### ISSUE TITLE
Availability message

### ISSUE THREAD

**Issue by johnnyq** [cupcakearmy/cryptgeon#24]
We are using Cryptgeon on a server that I host for clients to send files securely to us.

Most of the clients have been calling regarding  the message below before they send out a file. Is there anyway to remove or replace it. This will reduce the amount of explanations.

availability:
the note is not guaranteed to be stored as everything is kept in ram, if it fills up the oldest notes will be removed.
(you probably will be fine, just be warned.)

Thank you for your time on this project and giving back to the Free and Open Source Community. Keep up the good work!

**Comment by cupcakearmy** [comment]
Definetely doable. Will add in the next release.

P.S. if your company is using this for paying clients (which is awesome) and i'm basically implementing features for your clients on my free time I'll just... drop a link... to the donations box.... https://github.com/sponsors/cupcakearmy 😉

**Comment by cupcakearmy** [comment]
Check out the `THEME_TEXT`
