### ISSUE TITLE
note sharing just does not work

### ISSUE THREAD

**Issue by koveper** [cupcakearmy/cryptgeon#25]
You should be able to reproduce the error while trying to share a note. The link generates successfully but the note is not available under the link.

**Comment by cupcakearmy** [comment]
I think I messed up the router in moving to the newer actix version. Thanks for reporting!

**Comment by cupcakearmy** [comment]
Is fixed, docker image is being built & uploaded. https://github.com/cupcakearmy/cryptgeon/actions/runs/1938005302
