### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by ficoquery** [cupcakearmy/cryptgeon#29]
It would be well to update the readme to include further Installation details and more up-to-date information.

Example:

Development Installation:

Requirements:
PNPM? | What version?
Rust? | What version? | Rust Nightly?
.....? | What version?

Installation Options:

1. Docker
Steps...

2.
Steps...

3.
Steps...

__________________

Is pnpm i ; pnpm install, pnpm init? https://github.com/cupcakearmy/cryptgeon/blob/main/README.md#development

I am currently having errors and cant source the cause. https://github.com/cupcakearmy/cryptgeon/discussions/28

**Comment by cupcakearmy** [comment]
Just tested on a fresh macos machine. works perfectly. feel free to reopen if needed
