### ISSUE TITLE
Redis support

### ISSUE THREAD

**Issue by agates4** [cupcakearmy/cryptgeon#33]
Is it possible to add Redis support so that secrets are not lost when the server crashes or restarts or redeploys?

**Comment by cupcakearmy** [comment]
It's something I've been thinking about. Definitely more modern than memcache. I need to see what the memory limits are though.

**Comment by agates4** [comment]
From what i've seen that limit is `4 GB`

**Comment by cupcakearmy** [comment]
https://redis.io/docs/manual/data-types/#strings

Looks as it's 512MiB

**Comment by agates4** [comment]
Right ~ sorry, I mean the max of 4gb is related to total memory usage
https://redis.io/docs/reference/optimization/memory-optimization/#using-32-bit-instances

**Comment by cupcakearmy** [comment]
But that only applies to 32 bit machines, which should be basically unexisting at this point :) AFAIK there is no real limit to the total storage, only of single elements.

Now with memecache we can set custom size limits in the gigabyte size and going to redis would either imply:
1. Limiting the max size of text/files
2. Writing wrapper code to spread larger chunks into multiple entries.

Not sure what is better.

**Comment by agates4** [comment]
I think a file size limit is a good first implementation that can be followed with chunking whenever the inspiration strikes

**Comment by agates4** [comment]
I sponsored the project because of how great the user experience focus functionality is!
Seeing this feature would make it absolutley killer .. :)

**Comment by cupcakearmy** [comment]
Thanks for supporting open source work!
WIll be a 2.0 release def :)
512mb seems also a very reasonable limit for now xD
Hope I get around soon, kind of in the middle of a master thesis so can't promise anything 😅
