### ISSUE TITLE
Any chance we can use a custom logo?

### ISSUE THREAD

**Issue by jasonrojas** [cupcakearmy/cryptgeon#34]
Is there any way to use a custom logo?

**Comment by cupcakearmy** [comment]
The project is MIT, so tecnically you can do whatever you want with it :)
I guess you are asking for some way to easily customize it?
The question is how to go about it? maybe an url you can add as env variable?

**Comment by cupcakearmy** [comment]
Check out `THEME_IMAGE` https://github.com/cupcakearmy/cryptgeon#environment-variables

**Comment by deg749Goroe3** [comment]
Hello, is there any environment for dark logo theme too?

**Comment by cupcakearmy** [comment]
The dark theme is applied by the os settings. If your os is dark, the site will be dark. Don't want to force that on the user.

**Comment by deg749Goroe3** [comment]
> The dark theme is applied by the os settings. If your os is dark, the site will be dark. Don't want to force that on the user.

I meant that for light theme, I should use a different logo color =) But, thank you for the answer.

**Comment by deg749Goroe3** [comment]
No suggestions at all. I think I can use grey color =D. Thanks
