### ISSUE TITLE
Bigger files cannot be uploaded.

### ISSUE THREAD

**Issue by canlot** [cupcakearmy/cryptgeon#35]
Hello,

i'm running the latest cryptgeon version on docker.
My docker-compose file:

`version: '3.7'

services:
  memcached:
    container_name: memcached_cryptgeon
    image: memcached:1-alpine
    restart: unless-stopped
    entrypoint: memcached -m 512M -I 20M
    ports:
      - 11211:11211

  app:
    image: cupcakearmy/cryptgeon:latest
    depends_on:
      - memcached
    environment:
      SIZE_LIMIT: 10MiB
    ports:
      - 80:5000
`
When i try to upload files below 10 MByte i get an error that the file couldn't bei uploaded.
File is only 8.9 MByte.

![image](https://user-images.githubusercontent.com/7008555/177567721-d72a2ab9-e544-45df-9e83-fd775c913367.png)
![image](https://user-images.githubusercontent.com/7008555/177567800-a25641b7-a35e-452b-8d66-7d452ef569ed.png)

**Comment by cupcakearmy** [comment]
Could you try the 2.0 version with redis?

**Comment by cupcakearmy** [comment]
I did some investigation. So a PDF file of 3,8 MB blows up to 9.58 mb after encryption. This should not be the case. In theory file sizes should stame the same +- some padding.

I would gues this is the issue and would defentely understad why this happens. I'm quite sure this is due of the hex encoding. Will see what we can do.

**Comment by canlot** [comment]
Thank you for investigating this. I understand only trainstation :-D :-> when i am looking at the rust code.

**Comment by cupcakearmy** [comment]
It's actually all frontend. The files need to be encoded with printable characters.
I was using hex (base16) and switched to base64 now. this is the most efficient for sending it over json afaik.
It leaves an approx 35% encoding overhead. this means that if the server is configured with `4 MiB` the client will now show a max file size of `2.96 MiB`.
