### ISSUE TITLE
Unauthenticated Paths when limiting note creation to authentik users

### ISSUE THREAD

**Issue by troubleshootme** [cupcakearmy/cryptgeon#48]
I had previously used authentik proxy to limit access to note creation, but used:
^/note
as an unauthenticated path to allow guests to view the notes. 

This no longer appears to be working.

I'm assuming I need to add a few more now, any help would be greatly appreciated.

**Comment by cupcakearmy** [comment]
If all you want to do is limit note creation:
Deny `POST` methods to `/api/notes/`.
