### ISSUE TITLE
Default to Dark Mode?

### ISSUE THREAD

**Issue by xardoniak** [cupcakearmy/cryptgeon#5]
Hi there,
Thanks for creating this webapp - its super cool!

I'm struggling to find the night mode toggle though? Is it possible to default to dark mode?

Thanks,

**Comment by cupcakearmy** [comment]
Thanks for the kind words. the dark mode toggles with the system theme, but I can switch the theme to be dark first and light if the user agent chooses to.
And add a switch :)

**Comment by cupcakearmy** [comment]
Default is still system theme, if the system is unset dark mode is the default now.
There is now a manual override in the bottom left

**Comment by xardoniak** [comment]
Thanks mate!
