### ISSUE TITLE
Support for redis authentication 

### ISSUE THREAD

**Issue by hatesyourface** [cupcakearmy/cryptgeon#50]
Would the project consider adding the ability to use authenticated redis servers?

**Comment by cupcakearmy** [comment]
This should work already.
Check the connection stirng: https://docs.rs/redis/latest/redis/#connection-parameters
An example using `requirepass foobared` in the config and the redis server ip `1.2.3.4`, you would use `REDIS=redis://default:foobared@1.2.3.4`.

Feel free to open again if you are having issues
