### ISSUE TITLE
Can the service work with the POST method?

### ISSUE THREAD

**Issue by PenguinIsEvil** [cupcakearmy/cryptgeon#54]
I'm trying to come up with a CURL request like this:

#!/bin/bash
data=LOGIN
password=123PASSWD
note_link=$(curl -s 'https://cryptgeon.nicco.io' \
    -H 'X-Requested-With: XMLHttpRequest' \
    --data-urlencode "data=$data" \
    --data "has_manual_pass=false&duration_hours=0&dont_ask=false&data_type=T&notify_email=&notify_ref=" \
    | jq -r --arg arg $password '.note_link + "#" + $arg')
echo "note URL is $note_link"

but it doesn't work

**Comment by cupcakearmy** [comment]
Yes and no. So the encryption is handled by the client, not the server.
This means you can store and send data but the encryption needs to happen on your side. **The server does not know anything about encryption**.

```bash
#!/bin/bash

# Creating a link with data
LINK_ID=$(curl -s --location --request POST 'https://cryptgeon.nicco.io/api/notes/' \
  --header 'Content-Type: application/json' \
  --data-raw '{
    "contents": "Some content that is encrypted",
    "views": 1,
    "meta": "{\"type\":\"text\"}"
  }' | jq -cr '.id');
echo $LINK_ID;

# Getting the link
CONTENTS=$(curl -s --location --request DELETE "https://cryptgeon.nicco.io/api/notes/$LINK_ID" \
  --data-raw '' | jq -cr '.contents');
echo $CONTENTS;
```
