### ISSUE TITLE
CLI client

### ISSUE THREAD

**Issue by cupcakearmy** [cupcakearmy/cryptgeon#55]
Some have asked about the possibility of using cryptgeon from the cli.
(#54 and https://discord.com/channels/252403122348097536/912714340157755482/1016073982757322863)

However while the app already uses Rest and using the endpoints is not an issue, encryption is handled by design in the front end, therefore the server is agnostic about the contents of the data, wether it's encrypted or not.

Goals:
- have a CLI client that is compatible with macOS, Linux and maybe windows?
- should be able to encrypt and decrypt from links
- maybe start with text and then enable also file upload and download

Anyone interested: leave feedback and comments below so we can do something together here :)

**Comment by solick** [comment]
Hi @cupcakearmy thanks for this great peace of code! One question, do I understand you correctly that it is already possible to use the api? I was looking for this feature but did not found anything. An API which could be use for automated generation of messages would be interesting eg for delivering credentials etc. during automated server or user management etc.

**Comment by solick** [comment]
understood. But wouldn't it be worth spending the frontend an api? I would be not more than 2 endpoints, one for encryption, one for version?

**Comment by solick** [comment]
yes sorry. I mean because the frontend is taking care about the encryption etc. the functions are already there. What is needed is an api endpoint from the frontend which uses the functions of the frontend to generate the messages, and return the url for further usage.

**Comment by cupcakearmy** [comment]
Maybe lets chat on discord :) https://discord.com/invite/nuby6RnxZt
