### ISSUE TITLE
Title tag & favico

### ISSUE THREAD

**Issue by mojoaar** [cupcakearmy/cryptgeon#62]
Hi,

Would it be possible to implement variables to be able to set the title tag and a favicon?

**Comment by cupcakearmy** [comment]
Definitely:)

**Comment by cupcakearmy** [comment]
Added in v2.0.4

**Comment by deg749Goroe3** [comment]
This features don't available yet on latest docker version am I right?

**Comment by cupcakearmy** [comment]
Yes, the build failed for some reason. I'll restart it

**Comment by Surgical71** [comment]
Any update on this? I do not see the latest version added to Docker hub?
https://hub.docker.com/r/cupcakearmy/cryptgeon

**Comment by cupcakearmy** [comment]
The github action runs out of memory when building rust. Need to check

**Comment by cupcakearmy** [comment]
The x86 images are pushed, arm is still building

**Comment by deg749Goroe3** [comment]
> The x86 images are pushed, arm is still building

It looks like x86 images don't push yet, only arm, because I can't start 2.0.4 on x86 Ubuntu system.

**Comment by cupcakearmy** [comment]
See here: https://github.com/cupcakearmy/cryptgeon/issues/64
