### ISSUE TITLE
standard_init_linux.go:230: exec user process caused: exec format error

### ISSUE THREAD

**Issue by mariushosting** [cupcakearmy/cryptgeon#64]
Can't use the latest version 2.0.4 no errors in version 2.0.3
I get an error message in the logs that say the following: standard_init_linux.go:230: exec user process caused: exec format error

**Comment by cupcakearmy** [comment]
Thanks for reporting! Def. a bug, probably something with the new docker build system

**Comment by Vexz00** [comment]
Same problem here. Removing the docker container and re-deploying doesn't fix the issue.

**Comment by juanmanuelbc** [comment]
Same error here.

Maybe related question: `MEMCACHE` Environment Variable, is not being used any more?

Thanks...

**Comment by cupcakearmy** [comment]
Ok so what happened:

1. I split the arm and x86 builds.
2. The x86 finishes first
3. The arm one finishes later, overrides the release, so only arm64 images are available, which fail on x86

I'll put the pipelines back together

**Comment by cupcakearmy** [comment]
Should be fixed now in v2.0.5
