### ISSUE TITLE
View count has no minimum value

### ISSUE THREAD

**Issue by TinsellyCone** [cupcakearmy/cryptgeon#66]
The view count under advanced does not have a minimum value, and thus can be set to a negative number of views. If you click create note, it just gives an error. I think this could be corrected by adding the min property to the input field.

![Screenshot 2022-11-11 at 20-17-38 cryptgeon](https://user-images.githubusercontent.com/60909484/201449706-2ce38ec7-0a62-432d-812a-abb30d01a302.png)

**Comment by cupcakearmy** [comment]
Thanks for reporting :) Should be released in the next minutes/hour
