### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by alitalipcalikoglu** [cupcakearmy/cryptgeon#70]
I'm getting this error when building with the Dockerfile file.

![Docker file build error](https://user-images.githubusercontent.com/62916930/209539617-55c42c11-cc08-4de6-b68b-86aced3e5fa5.png)

**Comment by cupcakearmy** [comment]
Can replicate, thanks for opening the issue :)

**Comment by cupcakearmy** [comment]
The issue is vite 3 and not 4 and svelte kit being stable now

**Comment by cupcakearmy** [comment]
The latest master should build now, will do a release later

**Comment by cupcakearmy** [comment]
Should be fixed, feel free to reopen :)
