### ISSUE TITLE
Translate about page

### ISSUE THREAD

**Issue by cupcakearmy** [cupcakearmy/cryptgeon#73]
Strategy:
- lokalise?
- some kind of static svelte markdown?

**Comment by Rooyca** [comment]
Hey! I would like to help with Spanish translation.

**Comment by cupcakearmy** [comment]
Hey @Rooyca , thanks! I can add you to the lokalise project for spanish, would be awesome.
The about page still needs to be done

**Comment by Rooyca** [comment]
Yeah! Please add me. 
In the meantime I'll translate the about page.

**Comment by cupcakearmy** [comment]
I've invited you to the project at your personal email
