### ISSUE TITLE
Secret should not be a normal part in the url

### ISSUE THREAD

**Issue by ThisIsBenny** [cupcakearmy/cryptgeon#8]
Hi, nice looking app 😊

But I have one notice for you, you should not put the secret as normal part in the url like this:

https://cryptgeon.nicco.io/note/18l0rBija8mShKYjSUj49tL9TcTgzVYWMiT6E3RrmSRJw2xwQ0k1OzJxbb2oJuENDZRJ3tUsmFf5266DMithSVV/6565023d2d98cfd1c0fc08726d93e39bede97473c7528bd3f8bf4bc037350159

The problem with this URL is that the secret will send to the server and with a man in the middle attack, someone is able to see the key. Or if you are not delete the note after one visit, you can see the URL in the Access Logs and get the secret from there. If the note is still there, someone can see also the note.

<img width="1680" alt="Bildschirmfoto 2021-05-16 um 09 40 56" src="https://user-images.githubusercontent.com/66417262/118389615-f9289480-b62a-11eb-82c6-a8da3ad285ec.png">

You can use a `#` for the URL part with the secret. The part with the `#` will be not send from the browser to the server.
Your client app is still able to read this key from the key

https://cryptgeon.nicco.io/note/18l0rBija8mShKYjSUj49tL9TcTgzVYWMiT6E3RrmSRJw2xwQ0k1OzJxbb2oJuENDZRJ3tUsmFf5266DMithSVV#6565023d2d98cfd1c0fc08726d93e39bede97473c7528bd3f8bf4bc037350159

privnote is also using a `#` 😉 https://privnote.com/JkRrzfWk#W4UuuU9M2

**Comment by cupcakearmy** [comment]
Thanks for the thoughts :)
The mim attack is not possible, https encrypts path, query and everything execpt the domain name that is used to enstablish the connection.

That said, while the server itself never logs paths, there is no reason to send it, you are right :)
The attack of on logs is actually a possible vector if using a reverse proxy on the server that logs stuff.

Will fix it :)

**Comment by ThisIsBenny** [comment]
Hi, you are write. The path is encrypted via TLS. But there are a attacks to break TLS: https://www.imperva.com/learn/application-security/man-in-the-middle-attack-mitm/

I don‘t know how many attacks are still valid, but if you will fix it, then these possible attacks can be ignored 😊

**Comment by cupcakearmy** [comment]
Yes, a broken TLS version of course would be an issue xD but we would have way bigger problems if that were the case.

I've fixed it, waiting for the testing pipeline to create the release. It' been in the queue for 40 min now 🙄 https://github.com/cupcakearmy/cryptgeon/actions/runs/846706140

**Comment by cupcakearmy** [comment]
After some hours of github actions being down we got it :)
