### ISSUE TITLE
Bigger file size support?

### ISSUE THREAD

**Issue by drustan** [cupcakearmy/cryptgeon#86]
Hello,

First of all, thanks for the amazing application 👏

I'm wondering why the maximum file size limit is only 512 Mib? Is there any way this could be extended to 5Gib for instance?

**Comment by cupcakearmy** [comment]
Thanks! ❤️ 
This is a hard limit in redis https://redis.io/docs/data-types/strings/
One could spread it across multiple keys in theory, but raises the complexity.
