### ISSUE TITLE
Ability to only allow view-based shares?

### ISSUE THREAD

**Issue by jasonrojas** [cupcakearmy/cryptgeon#9]
Is there a way we can disable the functionality of the time based views?
Ie only allow notes to be created that are destroyed after the first view?
Thanks.

**Comment by cupcakearmy** [comment]
That is already the case. It is time OR view based, not both. The text in the interface should make it clear in theory.
Btw the default behavior is exatcly that: no time contraint, destroyed after 1 view.
Feel free to reopen if I did not unterstand correctly :)
