### ISSUE TITLE
Health check

### ISSUE THREAD

**Issue by drustan** [cupcakearmy/cryptgeon#92]
Hello!

Currently, we lack a method to make sure all necessary components are running smoothly, to guarantee the service is working fine.

For instance, if the connection with Redis fails, the service may still appear fully operational, displaying the homepage, until an attempt is made to create a secret, resulting in an error.

Is it possible to implement a Redis database access check when starting the app? Or it could be a /health route doing the checks.

Thanks much for making Cryptgeon by the way ;-)

**Comment by cupcakearmy** [comment]
Great suggestion! I'd say both should be implemented.
