### ISSUE TITLE
[Bug] cannot reach redis...

### ISSUE THREAD

**Issue by juanmanuelbc** [cupcakearmy/cryptgeon#99]
Since I tried to update from v2.3.0 to newer versions v2.3.1, v2.3.2 and v2.3.3 I'm getting 'cannot reach redis' error.

Going back to v2.3.0 it's working again.

Here is container registry of the error with 'RUST_BACKTRACE=1': [cryptgeon.csv](https://github.com/cupcakearmy/cryptgeon/files/12484231/cryptgeon.csv)

I'm deploying the container with this docker CLI command: `docker run -d --name=cryptgeon -e MEMCACHE=”memcached:11211” -e SIZE_LIMIT=4MiB -p 8000:8000 cupcakearmy/cryptgeon`; if you have any idea to resolve this issue, I'll be pleased to test it...

Thank you!!!

**Comment by juanmanuelbc** [comment]
> wait... version 2 moved from memcached to redis, memcached should not work xD

I can confirm that it works, because I have it working with v2.3.0...

I'll change the stack to use redis with `latest` version ASAP...

**Comment by cupcakearmy** [comment]
Thats... interesting to say the least xD
Maybe they have a similar enough api? it really should not be working with memcached xD
